### ISSUE TITLE
Simplify map by hiding assembly boundaries

### ISSUE THREAD

**Issue by answerquest** [publicmap/electionmap#14]
Would it be possible to keep only Parliamentary Constituencies boundaries and labels? The Assembly Constituencies have been marked different and lighter which is good, but the map starts to get quite confusing as we zoom in. When we're seeing things at state level (around z=7) it's fine. But once we go deeper, the other map features like roads start appearing, the AC labels start getting prominent and things get confusing; plus the map can look quite unfamiliar from end user's perspective, who would be more familiar with look and feel of google maps.

My ask : let's disable Assembly Constituencies if Lok Sabha Elections are the target at this point. 

Else (and maybe better), let's have a way to switch on or off both the PC and AC layers.
And if we take that option, then perhaps changing to satellite imagery is also possible, for helping people find the harder-to-find places.

**Comment by planemad** [comment]
Good feedback, the map is definitely overloaded with information.

The AC boundaries are not relevant right now, will turn it off.

**Comment by planemad** [comment]
Done

![new1](https://user-images.githubusercontent.com/126868/55679540-10b0d180-592b-11e9-94c7-58198bf0f978.gif)
