### ISSUE TITLE
If user location is outside India, default to some center-point

### ISSUE THREAD

**Issue by batpad** [publicmap/electionmap#23]
Right now, if someone is checking the site from outside the country, it will jump to their location, wherever it maybe.

We should:

 - Define a BBOX bounds that roughly encompasses the Indian subcontinent
 - Check if the users location falls inside of it
 - If not, DON'T zoom to user location, just remain at zoomed out map of India

Let me know if this might be something someone might be able to / willing to take on? Happy to support / outline better what needs to be done and where :)

cc @SrihariThalla

**Comment by DaxServer** [comment]
Instead of defining the BBOX ourselves, how about reverse geocoding the
location and check if it is India or not and proceed from there?

It's rather more accurate and no manual work ;)

**Comment by batpad** [comment]
There maybe a simpler fix yet :-) - can probably just define a `maxBounds` on the map or so. I can look into this. I'd rather avoid another network request / dependency on a geocoding service for this - like we shouldn't affect performance for 99% of our users (from India) - for this edge case - just restricting the map to some reasonable bounds should prevent the case of someone being shown a zoomed in map of some foreign place where they are and being not sure how this is supposed to work :-)

**Comment by batpad** [comment]
Duh - there's already a `maxBounds` on the map 🤦‍♂️ thanks @planemad - I think that's enough and we should not worry about this. Apologies for opening this issue :-)
