### ISSUE TITLE
Need to check the dates

### ISSUE THREAD

**Issue by answerquest** [publicmap/electionmap#3]
ECI Official site carrying notifications for schedules, phases:

https://eci.gov.in/general-election/general-elections-2019/

Our mapbox query says Pune (34) goes to polls in Phase 4, 29 April. 
But Pune is not present in the Phase 4 notification, and is listed in the Phase 3 notification.

**Comment by answerquest** [comment]
Update : Got all the 4 phases' official notifications checked by a volunteer - apart from Pune's there are no changes needed.

**Comment by planemad** [comment]
👍 Pune date has been corrected to phase 3
