### ISSUE TITLE
throttle queries

### ISSUE THREAD

**Issue by answerquest** [publicmap/electionmap#40]
These snippets might help:

```
// global variable, declare outside of all functions
globalBusy = false;
```

In the loop where we get the query result and put on output:
```
globalBusy = true;
setTimeout(function(){ 
    globalBusy=false; 
}, 5000); 
// num secs * 1000
```

When the user pins a location, before proceeding to making the API call,

```
if(globalBusy) return;
```

**Comment by planemad** [comment]
https://github.com/publicmap/electionmap/pull/44 takes care of reducing API calls
