### ISSUE TITLE
Map does not zoom in after device geolocation

### ISSUE THREAD

**Issue by planemad** [publicmap/electionmap#41]

**Comment by DaxServer** [comment]
@planemad The `zoom` param's missing @ https://github.com/publicmap/electionmap/blob/133b73c6a2ec33043f8b7f35cd7019dc1640c5b0/js/show-data-at-point.js#L16

Also, it seems there is a redundant `map.flyTo` @ https://github.com/publicmap/electionmap/blob/133b73c6a2ec33043f8b7f35cd7019dc1640c5b0/js/locate-user.js#L75

It seems the latest `map.flyTo` is obeyed
* https://sriharithalla.github.io/electionmap
* https://github.com/SrihariThalla/electionmap/commit/ca557e58205a0e4cc72f5a1e9c36505266f86be2

**Comment by planemad** [comment]
👍 PR?

**Comment by DaxServer** [comment]
Can you handle it? I don't have access to my laptop until Monday.

**Comment by DaxServer** [comment]
I am also thinking as IP Geolocation on mobile devices is not accurate, should we zoom in up to 6 (or other) instead of 9?
