### ISSUE TITLE
https://electionmap.in/ URL shows Privacy error

### ISSUE THREAD

**Issue by answerquest** [publicmap/electionmap#52]
Typically site names work even without the www; so in quick typing I'd shared this link : https://electionmap.in  but now on check I realizing it's not working :(  

If we do just http://electionmap.in then it redirects but the https gives error.

**Comment by planemad** [comment]
This is in the domain settings, what should it look like? 
<img width="1044" alt="Screen Shot 2019-04-13 at 5 35 38 PM" src="https://user-images.githubusercontent.com/126868/56079471-97294f80-5e12-11e9-9313-16b26660a339.png">

cc @batpad

**Comment by planemad** [comment]
Also not sure if this is on the Github end

<img width="474" alt="Screen Shot 2019-04-13 at 5 37 00 PM" src="https://user-images.githubusercontent.com/126868/56079485-d5267380-5e12-11e9-8276-dd9a30c4f989.png">

**Comment by planemad** [comment]
Github pages settings

<img width="948" alt="Screen Shot 2019-04-14 at 12 31 10 AM" src="https://user-images.githubusercontent.com/126868/56084155-ab8a3e00-5e4c-11e9-9780-8ce149f7d1f4.png">

**Comment by planemad** [comment]
@answerquest @batpad updated the CNAME on Github to `electionmap.in` and it seems to have fixed it.

https://electionmap.in/
