### ISSUE TITLE
Locate map at user position on opening page

### ISSUE THREAD

**Issue by planemad** [publicmap/electionmap#6]
Map should load centered on users current position using GPS geolocation or fallback to geoip location.

Free geoip server: https://publicmap-freegeoip.herokuapp.com/json/ 

cc @batpad

**Comment by batpad** [comment]
This should be done!

It now uses browser geolocation and if that is not got within 2 seconds of the page, queries the IP location end-point and uses that (but is always over-ridden with browser geolocation when / if that becomes available).

Personally, I'd almost rather just get rid of the IP location, but we can make a separate issue about that.

Closing this now :-)
