### ISSUE TITLE
mobile view gives 2-step scrolling experience

### ISSUE THREAD

**Issue by answerquest** [publicmap/electionmap#9]
In mobile view the bottom panel was first scrolling in itself but not entirely (ie we cannot see the bottom part of the box); and then the whole page was scrolling up anyways if we pulled it more. I could not find a way to prevent the whole page from scrolling anyways. So in the reverse direction, if I disabled that info box's internal scrolling at least the mobile experience is less 2-steppy.

Proposal to change, in index.html, this:
```
<div class='viewport-third h-auto-ml hmax-full bg-white round-ml shadow-darken5 scroll-auto'>
```
to this:
```
<div class='viewport-third h-auto-ml hmax-full bg-white round-ml shadow-darken5'>
```
That will eliminate internal scrolling in info-box. I rather prefer to keep that but make the page strictly 100% of mobile screen height, but don't know how to do that, so this is an alternative for making it one step smoother on mobile : page scrolls normally when you pull the info panel up.

**Comment by batpad** [comment]
@answerquest this PR should improve things slightly: https://github.com/publicmap/electionmap/pull/21

Though some of the issues you mention probably still exist. Could you please test the above PR? And if your proposed change above still looks good, am happy to review that as a PR, but it sounds reasonable to me.

**Comment by planemad** [comment]
@answerquest this looks mostly resolved now, do reopen if theres more to do here.
